//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSCF.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personalscfEntities2 : DbContext
    {
        public personalscfEntities2()
            : base("name=personalscfEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rl_usuario_lancamento> rl_usuario_lancamento { get; set; }
        public virtual DbSet<tb_conta> tb_conta { get; set; }
        public virtual DbSet<tb_lancamento> tb_lancamento { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
    }
}
