//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSCF.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rl_usuario_lancamento
    {
        public string ID { get; set; }
        public string ID_User { get; set; }
        public string ID_Lancamento { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_lancamento tb_lancamento { get; set; }
    }
}
