//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSCF.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_conta()
        {
            this.tb_lancamento = new HashSet<tb_lancamento>();
        }
    
        public string ID { get; set; }
        public string NomeBanco { get; set; }
        public string TipoConta { get; set; }
        public Nullable<System.DateTime> DataExclusao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_lancamento> tb_lancamento { get; set; }
    }
}
